### ISSUE TITLE
Highlight next line when scrolling through candidates.

### ISSUE THREAD

**Issue by grolongo** [oantolin/icomplete-vertical#15]
Hello, first of all thank you for this package, it made the transition from Ivy to Icomplete easier since v27 for me.

One thing I liked better when using Ivy/Counsel though, using the default settings to find a recentf-list file for example, is when you are scrolling the list to find your file, the selection highlight moves down the lines until it reaches the bottom.

Right now with Icomplete and using `icomplete-forward-completions` or `icomplete-backward-completions` with the keybinds  the highlight stays on the first line and the whole list moves up, somehow this gets me dizzy when I have a long list.

How would it be possible to change this behavior so it can replicates what Ivy does? I know this is probably not related to your package specifically but about Icomplete in general but since I'm using it exclusively in vertical mode I thought to ask here directly.

Anyway if I'm not clear enough just let me know and I will provide screenshots to better explain myself (not english native).

Thanks for the help.

**Comment by oantolin** [comment]
Hi @grolongo! 

I know exactly what you mean about the UI. I think changing that is outside the scope of this package, because it would basically involve rewriting a good chunk of icomplete. My package is a very thin layer over icomplete that just improves the formatting you'd get if you simply set the icomplete separator to be a newline. It does not attempt to change the basic mechanism of icomplete at all.

If you want a similar lightweight package that does highlight the current selection and move the highlight up and down without rotating the list, I highly recommend [Selectrum](https://github.com/raxod502/selectrum).

I hate to close issues as WONTFIX, but I think it is warranted in this case. Sorry.

PS. Your English is perfect, you should stop including disclaimers in your posts!

**Comment by grolongo** [comment]
Understood!

Thank you for suggesting Selectrum. I just looked at it, seems like the best balance for me between Ivy and Icomplete, coupled with prescient.
