### ISSUE TITLE
icomplete-vertical-annotate should be optimized more if possible

### ISSUE THREAD

**Issue by minad** [oantolin/icomplete-vertical#18]
If I do M-x and scroll around (keeping down pressed) with marginalia-mode the display hangs and updates after releasing the key. This does not happen if marginalia-mode is disabled. I am using Emacs 27.1. See https://github.com/minad/marginalia/issues/25 for the original issue.

**Comment by minad** [comment]
When profiling 68% of the time is spent in icomplete-vertical-annotate. From that 12% is used by marginalia-annotate-binding. Something is going on in icomplete-vertical-annotate which deserves optimization.

**Comment by oantolin** [comment]
I was annotating all candidates and now just annotate the first `icomplete-vertical-prospects-height` candidates, should be snappier. I can't really tell since it didn't really feel slow on my computer before. I'll go over to minad/marginal#25 and as people to test the change.

There's no reason to waste time on invisible candidates so this is a good change even if it doesn't solve the slowdown.

**Comment by minad** [comment]
Cool, I try it out!

**Comment by oantolin** [comment]
I don't see any obvious way to speed up each invidual annotations, so I really hope this fixes the problem.

**Comment by minad** [comment]
Much better, thank you! This fixes the issue. Our annotators are already very fast! Selectrum originally did the same - annotating all candidates, then @clemera changed it such that annotations are lazy, see here https://github.com/raxod502/selectrum/issues/247
